apiVersion: v1
kind: BuildConfig
metadata:
  labels:
  name: 3scale-toolbox-test-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
            agent any
            options { 
                skipDefaultCheckout()
                disableConcurrentBuilds()
            }
            stages {                
                stage("Run 3scale toolbox") {
                    agent {
                        label "jenkins-3scale-toolbox-agent"
                    }
                    steps {
                        sh "3scale --help"
                    }
                }    
            }
        }
    type: JenkinsPipeline