apiVersion: v1
kind: Service
metadata:
  labels:
    app: songs
  name: songs
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: songs