apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: songs
          resources:
            limits:
              memory: 256Mi
              cpu: 300m
            requests:
              memory: 256Mi
              cpu: 300m